-------------------------------------------------
--5.. Magnitude Analysis
-------------------------------------------------
/* Compare the measure values by categories*/


-- Find the total number of customers by countries
SELECT 
	country,
	COUNT(customer_number) as total_customers
FROM gold.dim_customers
GROUP BY country


-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_number) as total_customers,
FROM gold.dim_customers
GROUP BY gender


-- Find total products by category
SELECT 
	category,
	COUNT(product_id) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category?
SELECT 
	category,
	AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC


-- What is the total revenue generated for each category?
SELECT 
	pc.category,
	SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales as fs
LEFT JOIN gold.dim_products as pc
ON pc.product_key = fs.product_key
GROUP BY pc.category
ORDER BY total_revenue DESC

-- Find total revenue generated by each customer
SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
ON f.customer_key = c.customer_key
GROUP BY customer_id, c.first_name, c.last_name
ORDER BY total_revenue DESC


-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(f.quantity) as total_sold_items
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers as c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
